name: omni_jitsi_meet
description: Jitsi Meet Plugin - A plugin for integrating open source Jitsi Meet API in flutter. Jitsi Meet is secure, fully featured and allows completely free video conferencing made with https://jitsi.org, a collection of open source projects
version: 1.0.4
homepage: https://github.com/thorito/jitsi_meet
repository: https://github.com/thorito/jitsi_meet/tree/master/omni_jitsi_meet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  omni_jitsi_meet_platform_interface: ^1.0.4
  omni_jitsi_meet_web_plugin: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.thorito.jitsi_meet
        pluginClass: JitsiMeetPlugin
      ios:
        pluginClass: JitsiMeetPlugin
      web:
        default_package: jitsi_meet_web_plugin