name: omni_jitsi_meet_web_plugin
description: Jitsi Meet Web Plugin. A plugin for integrating open source Jitsi Meet API in flutter.
version: 1.0.5
homepage: https://github.com/thorito/jitsi_meet

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  meta: ^1.8.0
  flutter_web_plugins:
    sdk: flutter

  omni_jitsi_meet_platform_interface: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
